### ISSUE TITLE
Bot: Remove "snapshot only" pieces from the bot

### ISSUE THREAD

**Issue by daveomitchell** [BeautifulTrouble/beautiful-rising#90]
In keeping with what we decided for the website, I think it makes sense to remove the "snapshot only" pieces from the menu display in the bot, so that people could only access pieces for which gallery entries or full modules exist.

I'm marking this as "Priority 1" as I suspect this will significantly improve the user experience of the bot, and therefore affect the testing and evaluation that @DianaHajTPS is conducting.

**Comment by phillipadsmith** [comment]
I was actually just looking at that moments ago.

I can make that change today.

**Comment by daveomitchell** [comment]
👍 👍 :neckbeard:

**Comment by phillipadsmith** [comment]
Worked on this @daveomitchell, but it is actually not as straightforward as I had hoped because there's no easy or consistent way that I can figure out to determine what's a snapshot (and I'm assuming the same goes for gallery entries?).

Will try to circle back to this at my first opportunity this week, which might not be until Friday.

**Comment by adrian-the-git** [comment]
There's now a module-type key in each piece which contains one of: "full", "snapshot" or "gallery"

**Comment by phillipadsmith** [comment]
> I'm marking this as "Priority 1" as I suspect this will significantly improve the user experience of the bot, and therefore affect the testing and evaluation that @DianaHajTPS is conducting.

Deployed.
