### ISSUE TITLE
Arabic leaking through to English?

### ISSUE THREAD

**Issue by phillipadsmith** [BeautifulTrouble/beautiful-rising#99]
https://beautifulrising.org/tool/public-narrative-story-of-self-us-and-now-

<img width="538" alt="public_narrative__story_of_self__us__and_now_" src="https://cloud.githubusercontent.com/assets/34128/18104748/67c5f4ee-6eb1-11e6-84d2-df7aa215eb50.png">

**Comment by adrian-the-git** [comment]
I was asked to make the learn-more section and real-world-examples include content from all languages so this is a feature looking like a bug. @daveomitchell is this still desirable? 

Perhaps it should be sorted to prioritize the current language.

**Comment by daveomitchell** [comment]
You're right, Adrian -- it's showing up as designed. This was a learn-more link included by the author before the translated docs were available, and we felt it wasn't such a bad thing for English speakers to see non-English links now and then, since non-English speakers would be seeing a lot of them in the Spanish and Arabic versions...  Not worth spending time correcting for, I'd say, though if it's distracting, that link could now be moved to just the Arabic version of the doc.

**Comment by adrian-the-git** [comment]
@daveomitchell Hmm. It was my understanding that RWE's which were added to, say, an Arabic doc, would be visible in all languages. In this particular instance, the RWE in Arabic was added to the English doc, but it will continue to show up if moved to the Arabic doc because of this "filter through" feature.

**Comment by adrian-the-git** [comment]
@daveomitchell any vote to change this "all languages show up in real world examples" behavior? going once...

**Comment by daveomitchell** [comment]
Let's leave it for now... I'm assuming it's a change we could make if we suddenly get a lot of Spanish and Arabic RWEs being added and decide to streamline things... once we've budget for making such changes. :-/
